name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, core-service, chat-service, search-service, notification-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        if: contains(matrix.service, 'service') && matrix.service != 'core-service'
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Set up Go
        if: matrix.service == 'core-service'
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies (Node)
        if: matrix.service != 'core-service'
        run: |
          cd ${{ matrix.service }}
          npm install

      - name: Build Go service
        if: matrix.service == 'core-service'
        run: |
          cd core-service
          go build -v .

      - name: Deploy step (manual placeholder)
        run: echo "Ready to deploy ${{ matrix.service }} via Render"
